<?php declare(strict_types=1);

namespace KikCMS\Services\Util;

use DateTime;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Utility Service for handling DateTime objects
 */
class DateTimeService
{
    public function __construct(
        private readonly TranslatorInterface $translator
    ) {}

    /**
     * Convert a datetime string generated by a datepicker to DateTime.
     *
     * @param string|null $dateTime
     * @return DateTime|null
     */
    public function getFromDatePickerValue(?string $dateTime): ?DateTime
    {
        if ( ! $dateTime) {
            return null;
        }

        $date = DateTime::createFromFormat('Y-m-d', $dateTime);
        if ($date !== false) {
            return $date;
        }

        return DateTime::createFromFormat($this->getDateFormat(), $dateTime) ?: null;
    }

    /**
     * Get the default PHP date format for the current language.
     *
     * @return string
     */
    public function getDateFormat(): string
    {
        return $this->translator->trans('system.phpDateFormat', [], 'messages');
    }
}