<?php declare(strict_types=1);

namespace KikCMS\Services\Util;

use DateTime;
use IntlDateFormatter;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Utility Service for handling DateTime objects
 */
class DateTimeService
{
    // Todo: Dit mag er uit, en de code die het gebruikt, het nieuwe CMS hoeft geen rekening te houden met legacy code
    private const STRFTIME_REPLACES = [
        '%a' => 'E',
        '%A' => 'EEEE',
        '%d' => 'dd',
        '%e' => 'd',
        '%j' => 'D',
        '%u' => 'e', // not 100% correct
        '%w' => 'c', // not 100% correct
        '%U' => 'w',
        '%V' => 'ww', // not 100% correct
        '%W' => 'w', // not 100% correct
        '%b' => 'MMM',
        '%B' => 'MMMM',
        '%h' => 'MMM', // alias of %b
        '%m' => 'MM',
        '%C' => 'yy', // no replace for this
        '%g' => 'yy', // no replace for this
        '%G' => 'Y', // not 100% correct
        '%y' => 'yy',
        '%Y' => 'yyyy',
        '%H' => 'HH',
        '%k' => 'H',
        '%I' => 'hh',
        '%l' => 'h',
        '%M' => 'mm',
        '%p' => 'a',
        '%P' => 'a', // no replace for this
        '%r' => 'hh:mm:ss a',
        '%R' => 'HH:mm',
        '%S' => 'ss',
        '%T' => 'HH:mm:ss',
        '%X' => 'HH:mm:ss', // no replace for this
        '%z' => 'ZZ',
        '%Z' => 'v', // no replace for this
        '%c' => 'd/M/YYYY HH:mm:ss', // Buddhist era not converted.
        '%D' => 'MM/dd/yy',
        '%F' => 'yyyy-MM-dd',
        '%s' => '', // no replace for this
        '%x' => 'd/MM/yyyy', // Buddhist era not converted.
        '%n' => "\n",
        '%t' => "\t",
        '%%' => '%',
    ];

    public function __construct(
        private readonly TranslatorInterface $translator
    ) {}

    /**
     * Format a datetime according to the given pattern.
     * Supports both ICU patterns and legacy strftime placeholders (via translation table).
     *
     * @param string $pattern
     * @param DateTime|string|int $datetime
     * @return string
     */
    public function format(string $pattern, DateTime|string|int $datetime): string
    {
        // Handle Unix timestamp format (special case)
        if ($pattern === '%s' || $pattern === 'U') {
            if (is_string($datetime) || is_int($datetime)) {
                $datetime = new DateTime('@' . $datetime);
            }
            return $datetime->format('U');
        }

        // Replace legacy strftime placeholders with ICU equivalents
        if (str_contains($pattern, '%')) {
            $pattern = strtr($pattern, self::STRFTIME_REPLACES);
        }

        $formatter = new IntlDateFormatter(
            $this->translator->getLocale(),
            IntlDateFormatter::NONE,
            IntlDateFormatter::NONE,
            null,
            null,
            $pattern
        );

        return $formatter->format(is_numeric($datetime) ? '@' . $datetime : $datetime);
    }

    /**
     * Convert a datetime string generated by a datepicker to DateTime.
     *
     * @param string|null $dateTime
     * @return DateTime|null
     */
    public function getFromDatePickerValue(?string $dateTime): ?DateTime
    {
        if ( ! $dateTime) {
            return null;
        }

        $date = DateTime::createFromFormat('Y-m-d', $dateTime);
        if ($date !== false) {
            return $date;
        }

        return DateTime::createFromFormat($this->getDateFormat(), $dateTime) ?: null;
    }

    /**
     * Get the default PHP date format for the current language.
     *
     * @return string
     */
    public function getDateFormat(): string
    {
        return $this->translator->trans('system.phpDateFormat', [], 'messages');
    }
}