pages:
    label: menu.pages
    icon: view-grid
media:
    label: menu.media
    icon: image-outline
statistics:
    label: menu.statistics
    icon: google-analytics
users:
    label: menu.users
    icon: account-multiple-outline
settings:
    label: menu.settings