search_columns: ['name']
buttons:
    add:
        label: Add color
    delete: ~
headers:
    id: Id
    name: Name
    active: Active
cells:
    active:
        type: 'checkbox'
mobile_columns:
    - name
form:
    fields:
        name:
            type: 'text'
            label: 'Color name'
            validator:
                name: presence
        thought:
            type: 'text'
            label: 'What thought does this color bring to mind?'
        active:
            type: 'checkbox'
            label: 'Active'
rearrange: true
source:
    type: local