class: pages
search_columns: ['name.*']
headers_translate:
    name.*: general.name
    template: general.template
    slug.*: general.slug
    active.*: general.active
    id: general.id
cells:
    name.*:
        type: 'page'
    active.*:
        type: 'checkbox'
mobile_columns:
    - name.*
buttons:
    -   label: Add page
        action: add
        icon: 'mdi-plus'
    -   label: Delete
        action: delete
        icon: 'mdi-delete'
    -   label: 'Add new…'
        icon: 'mdi-menu'
        type: 'menu'
        items:
            -   title: 'Add link'
                icon: 'mdi-link-variant'
                action: 'add'
                addType: 'link'
            -   title: 'Add menu'
                icon: 'mdi-menu'
                action: 'add'
                addType: 'menu'
form_provider: KikCMS\Entity\Page\PageFormProvider
row_view_modifier: KikCMS\Entity\Page\DataTableModifier\PageViewRowDataModifier
source:
    model: KikCMS\Entity\Page\Page