buttons:
    -   label: Add section
        action: add
        icon: 'mdi-plus'
    -   label: Delete
        action: delete
        icon: 'mdi-delete'
headers:
    id: Id
    type: Type
mobile_columns:
    - type
row_view_modifier: KikCMS\Entity\PageSection\Modifier\PageSectionRowViewModifier
form:
    field_provider: KikCMS\Entity\PageSection\Provider\PageSectionTypeFieldsProvider
    field_provider_add: true
    fields:
        type:
            type: select
            label: Type
            item_provider: KikCMS\Entity\PageSection\Provider\PageSectionTypeOptionsProvider
            is_form_modifier: true
            validator:
                name: presence
                parameters:
                    required: true
rearrange: true
source:
    type: pdo
    model: KikCMS\Entity\PageSection\PageSection