buttons:
    add:
        label: Add image
    delete: ~
headers:
    id: Id
    name: Name
    image_id: Afbeelding
    display_order: Order
cells:
    active:
        image_id: image
mobile_columns:
    - image_id
form:
    fields:
        name:
            type: text
            label: Naam
            validator:
                name: presence
        image_id:
            type: filepicker
            label: Afbeelding
rearrange: true
source:
    type: local