class: pages
search_columns: ['name.*']
headers_translate:
    name.*: general.name
    template: general.template
    slug.*: general.slug
    active.*: general.active
    id: general.id
cells:
    name.*:
        type: page
    active.*:
        type: checkbox
mobile_columns:
    - name.*
buttons:
    add:
        label_trans: datatables.page.button.add_page
    delete:
        label_trans: datatable.button.delete
    add_new:
        label_trans: datatables.page.button.add_new
        icon: mdi-menu
        type: menu
        items:
            link:
                label_trans: datatables.page.button.add_link
                icon: mdi-link-variant
                action: add
                addType: link
            menu:
                label_trans: datatables.page.button.add_menu
                icon: mdi-menu
                action: add
                addType: menu
form_provider: KikCMS\Entity\Page\PageFormProvider
row_view_modifier: KikCMS\Entity\Page\DataTableModifier\PageViewRowDataModifier
source:
    model: KikCMS\Entity\Page\Page