content:
    label: section_fields.content
    type: richtext
    field: content.*.content
text:
    label: section_fields.text
    type: richtext
    field: content.*.text
image:
    label: section_fields.image
    type: image
    field: content.image
form:
    label: section_fields.form
    type: select
    field: content.form
    item_provider: form_options
title:
    type: text
    field: name.*
    label: general.name
    validator:
        name: presence
sections:
    type: datatable
    label: general.content
    instance: page_content
gallery:
    type: datatable
    label: fields.gallery
    field: content.gallery
    instance: page_images