richtext:
    label: sections.richtext
    fields:
        - content
richtext_image:
    label: sections.richtext_image
    fields:
        - content
        - image
richtext_gallery:
    label: sections.richtext_gallery
    fields:
        - content
        - gallery
image:
    label: sections.image
    fields:
        - image
overview:
    label: sections.overview
form:
    label: sections.form
    fields:
        - text
        - form