sections:
    richtext:
        label_trans: sections.richtext
        fields:
            - content
    richtext_image:
        label_trans: sections.richtext_image
        fields:
            - content
            - image
    image:
        label_trans: sections.image
        fields:
            - image
    overview:
        label_trans: sections.overview
fields:
    content:
        label_trans: Inhoud
        type: richtext
    image:
        label_trans: Afbeelding
        type: image