home:
    label_trans: templates.home
    fields: [ title, hero, sections ]

default:
    label_trans: templates.default
    fields: [ title, sections ]

project:
    label_trans: templates.project
    fields: [ title, image, content ]

blog:
    label_trans: templates.blog
    fields: [ title, content ]

overview:
    label_trans: templates.overview
    fields: [ title ]