home:
    label: templates.home
    fields: [ title, slider, sections ]

default:
    label: templates.default
    fields: [ title, sections ]

project:
    label: templates.project
    fields: [ title, image, content ]

blog:
    label: templates.blog
    fields: [ title, content ]

overview:
    label: templates.overview
    fields: [ title ]