tabs:
    page:
        label: datatables.page.tab.page
        field_provider: page_template
    seo:
        label: datatables.page.tab.seo
        fields:
            seo_title:
                field: seo.*.title
                type: text
                label: forms.page.seo.title
            seo_keywords:
                field: seo.*.keywords
                type: textarea
                label: forms.page.seo.keywords
            seo_description:
                field: seo.*.description
                type: textarea
                label: forms.page.seo.description
    advanced:
        label: datatables.page.tab.advanced
        fields:
            template:
                type: select
                label: general.template
                item_provider: page_template_options
                is_form_modifier: true
            slug:
                type: text
                label: general.slug
                field: slug.*
            identifier:
                type: text
                label: general.identifier
            active:
                type: checkbox
                label: general.active
                field: active.*